Locations Functions implemented
FAP-Cloud-Service/FAP-Backend pull request #26
Opened 2021-04-25 12:36 UTC by Mindia620

closes #9

2021-04-25 18:24 UTC, maltemorgenstern requested changes

2021-04-25 18:24 UTC, maltemorgenstern commented on FriendsAndPlaces/Functions/LocationsFunction.cs
> +            }
Das passt noch nicht, oder?
Es kommt kein Body, aber Parameter.

2021-04-25 18:24 UTC, maltemorgenstern commented on FriendsAndPlaces/Functions/LocationsFunction.cs
> +            var user = _databaseManager.GetUser(locationRequest.LoginName);
Warum brauchst du hier den User?

2021-04-25 18:24 UTC, maltemorgenstern commented on FriendsAndPlaces/Functions/LocationsFunction.cs
> +
Warum brauchst du die Formatting Settings?

2021-04-26 14:29 UTC, Mindia620 commented
@maltemorgenstern not sure where the error is, can you help me check?

2021-04-26 15:04 UTC, maltemorgenstern requested changes

2021-04-26 15:04 UTC, maltemorgenstern commented on FriendsAndPlaces/Models/Locations/Location.cs
> +
Leerzeile weg.

2021-04-26 15:04 UTC, maltemorgenstern commented on FriendsAndPlaces/Models/Locations/LocationRequest.cs
> +
Leerzeile weg.

2021-04-26 15:04 UTC, maltemorgenstern commented on FriendsAndPlaces/Functions/LogoutFunction.cs
> +        public IActionResult Run(
Das würde ich rückgängig machen - das kommt schon mit den anderen PR, sonst gibt es nur Konflikte.

2021-04-26 15:04 UTC, maltemorgenstern commented on FriendsAndPlaces/Functions/LocationsFunction.cs
> +
Leerzeile weg.

2021-04-26 15:04 UTC, maltemorgenstern commented on FriendsAndPlaces/Functions/LocationsFunction.cs
> +
Leerzeile weg.

2021-04-26 15:04 UTC, maltemorgenstern commented on FriendsAndPlaces/Functions/LocationsFunction.cs
> +                locationRequest.SessionId == null )
Zudem sollte auch` locationRequest.Location == null` geprüft werden

2021-04-26 15:04 UTC, maltemorgenstern commented on FriendsAndPlaces/Functions/LocationsFunction.cs
> +            bool success = _databaseManager.SetLocation(locationRequest.LoginName, locationRequest.Longitude, locationRequest.Latitude);
Hier muss dann `locationRequest.Location.Longitute` verwendet werden.

2021-04-26 15:04 UTC, maltemorgenstern commented on FriendsAndPlaces/Functions/LocationsFunction.cs
> +                sessionId == null )
Siehe oben: Check mit string.IsNullOrWhitespace Methode

2021-04-26 15:04 UTC, maltemorgenstern commented on FriendsAndPlaces/Functions/LocationsFunction.cs
> +            string sessionId = req.Query["sitzung"];
Kommentar anpassen und dahinter eine Leerzeile

2021-04-26 15:05 UTC, maltemorgenstern commented
@Mindia620 siehe Kommentare bzgl. des Fehlers.
Großteil sind sonst kosmetische Änderungen, die nicht super wichtig sind, aber nice to have wären 😉

2021-04-26 19:50 UTC, maltemorgenstern requested changes
Auf in eine letzte Runde 😉 

Die Parameter für "GetStandort" passen nicht, sonst nur Kosmetik.

2021-04-26 19:50 UTC, maltemorgenstern commented on FriendsAndPlaces/Functions/LocationsFunction.cs
> +            if (                string.IsNullOrWhiteSpace(locationRequest.LoginName) ||
Format kaputt.

2021-04-26 19:50 UTC, maltemorgenstern commented on FriendsAndPlaces/Functions/LocationsFunction.cs
> +            string sessionId = req.Query["sitzung"];
```suggestion
            // Read request parameters
            string loginName = req.Query["login"];
            string sessionId = req.Query["session"];
            string userId = req.Query["id"];
```

2021-04-26 19:50 UTC, maltemorgenstern commented on FriendsAndPlaces/Functions/LocationsFunction.cs
> +            }
Add check for userId

2021-04-26 19:50 UTC, maltemorgenstern commented on FriendsAndPlaces/Functions/LocationsFunction.cs
> +            var location = _databaseManager.GetLocation(loginName);
Use userId instead of loginName

2021-04-27 15:01 UTC, maltemorgenstern approved these changes
LGTM - aus meiner Sicht sind alle Themen umgesetzt denke ich 👍

2021-04-27 18:54 UTC, merged